export enum TipoNotificacao {
  CONTA_A_PAGAR = "CONTA_A_PAGAR",
  CONTA_A_RECEBER = "CONTA_A_RECEBER",
  COBRANCA_RECEBIDA = "COBRANCA_RECEBIDA",
  COBRANCA_PAGA = "COBRANCA_PAGA",
  SOLICITACAO_CONEXAO_ENVIADA = "SOLICITACAO_CONEXAO_ENVIADA",
}
