export const catalogoErros = {
  USUARIO_NAO_ENCONTRADO: -1,
  TOKEN_NAO_ENCONTRADO: -7,
  EMAIL_JA_CADASTRADO: -30,
  CAMPO_INVALIDO_OU_OBRIGATORIO: -90,
  ERRO_AO_AUTENTICAR_USUARIO: -91,
  TOKEN_EXPIRADO: -94,
  ERRO_INTERNO_DO_SERVIDOR: -999,
};
